services:
  # ==========================================
  # Infrastructure Services
  # ==========================================
  identity-db:
    container_name: identity-db
    image: postgres:18-alpine
    volumes:
      - identity-data:/var/lib/postgresql
      - ./user-service/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./user-service/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    environment:
      - POSTGRES_USER=${IDENTITY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${IDENTITY_POSTGRES_PW}
      - POSTGRES_DB=${IDENTITY_POSTGRES_DB}
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:8-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PW}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PW}", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

  catalog-db:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: catalog-db
    hostname: catalog-db
    volumes:
      - ./catalog-service/scripts/mongo-init:/docker-entrypoint-initdb.d
      - catalog-data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${CATALOG_MONGO_ADMIN_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${CATALOG_MONGO_ADMIN_PW}
      - MONGO_INITDB_DATABASE=${CATALOG_MONGO_DB}
    ports:
      - "27018:27017"
    restart: always
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-db:
    container_name: order-db
    image: postgres:18-alpine
    volumes:
      - order-data:/var/lib/postgresql
      - ./order-service/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    environment:
      - POSTGRES_USER=${ORDER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDER_POSTGRES_PW}
      - POSTGRES_DB=${ORDER_POSTGRES_DB}
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-db:
    container_name: inventory-db
    image: postgres:18-alpine
    volumes:
      - inventory-data:/var/lib/postgresql
      - ./inventory-service/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./inventory-service/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    environment:
      - POSTGRES_USER=${INVENTORY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${INVENTORY_POSTGRES_PW}
      - POSTGRES_DB=${INVENTORY_POSTGRES_DB}
    ports:
      - "5435:5432"
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # Application Microservices
  # ==========================================
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "4000:4000"
    environment:
      - HTTP_PORT=4000
      - DB_URL=postgresql://${IDENTITY_POSTGRES_USER}:${IDENTITY_POSTGRES_PW}@identity-db:5432/${IDENTITY_POSTGRES_DB}?sslmode=disable
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PW}
      - REDIS_DB=0
    env_file:
      - ./user-service/.env
    restart: unless-stopped
    depends_on:
      identity-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  catalog-service:
    build:
      context: .
      dockerfile: catalog-service/Dockerfile
    container_name: catalog-service
    ports:
      - "4001:4001"
      - "50050:50050"
    environment:
      - HTTP_PORT=4001
      - GRPC_PORT=50050
      - DB_URL=mongodb://${CATALOG_MONGO_USER}:${CATALOG_MONGO_PW}@catalog-db:27017/${CATALOG_MONGO_DB}?authSource=catalog-db&directConnection=true
      - DB_NAME=${CATALOG_MONGO_DB}
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PW}
      - REDIS_DB=1
    env_file:
      - ./catalog-service/.env
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    container_name: inventory-service
    ports:
      - "4002:4002"
      - "50052:50052"
    environment:
      - HTTP_PORT=4002
      - GRPC_PORT=50052
      - DB_URL=postgresql://${INVENTORY_POSTGRES_USER}:${INVENTORY_POSTGRES_PW}@inventory-db:5432/${INVENTORY_POSTGRES_DB}?sslmode=disable
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PW}
      - REDIS_DB=2
      - RMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - RMQ_RPC_SERVER=inventory_rpc_server
      - RMQ_RPC_CLIENT=inventory_rpc_client
      - RMQ_EXCHANGE=inventory.events
      - CATALOG_SERVICE_ADDR=catalog-service:50050
    env_file:
      - ./inventory-service/.env
    restart: unless-stopped
    depends_on:
      inventory-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      catalog-service:
        condition: service_started

  inventory-consumer:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    container_name: inventory-consumer
    command: [ "/app/event-consumer" ]
    environment:
      - DB_URL=postgresql://${INVENTORY_POSTGRES_USER}:${INVENTORY_POSTGRES_PW}@inventory-db:5432/${INVENTORY_POSTGRES_DB}?sslmode=disable
      - RMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - RMQ_EXCHANGE=inventory.events
      - RMQ_QUEUE_NAME=inventory.goods-received.q
      - RMQ_ROUTING_KEY=goods.received
      - LOG_LEVEL=info
      - CATALOG_SERVICE_ADDR=catalog-service:50050
    env_file:
      - ./inventory-service/.env
    restart: unless-stopped
    depends_on:
      inventory-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  inventory-publisher:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    container_name: inventory-publisher
    command: [ "/app/outbox-publisher" ]
    environment:
      - DB_URL=postgresql://${INVENTORY_POSTGRES_USER}:${INVENTORY_POSTGRES_PW}@inventory-db:5432/${INVENTORY_POSTGRES_DB}?sslmode=disable
      - RMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - RMQ_EXCHANGE=inventory.events
      - OUTBOX_POLL_INTERVAL=5s
      - OUTBOX_BATCH_SIZE=50
      - OUTBOX_MAX_RETRIES=5
      - LOG_LEVEL=info
    env_file:
      - ./inventory-service/.env
    restart: unless-stopped
    depends_on:
      inventory-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      inventory-consumer:
        condition: service_started

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    container_name: cart-service
    ports:
      - "4003:4003"
      - "50053:50053"
    environment:
      - HTTP_PORT=4003
      - GRPC_PORT=50053
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PW}
      - REDIS_DB=3
      - CATALOG_SERVICE_GRPC_ADDR=catalog-service:50050
    env_file:
      - ./cart-service/.env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      catalog-service:
        condition: service_started

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "4004:4004"
    environment:
      - HTTP_PORT=4004
      - DB_URL=postgresql://${ORDER_POSTGRES_USER}:${ORDER_POSTGRES_PW}@order-db:5432/${ORDER_POSTGRES_DB}?sslmode=disable
      - CART_SERVICE_GRPC_ADDR=cart-service:50053
      - CATALOG_SERVICE_GRPC_ADDR=catalog-service:50050
      - INVENTORY_SERVICE_GRPC_ADDR=inventory-service:50052
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PW}
      - REDIS_DB=4
    env_file:
      - ./order-service/.env
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      cart-service:
        condition: service_started
      catalog-service:
        condition: service_started
      inventory-service:
        condition: service_started

volumes:
  identity-data:
  catalog-data:
  redis-data:
  order-data:
  inventory-data:
  rabbitmq-data:

networks:
  default:
    name: micro-net
