package domain

import "errors"

var (
	ErrEmailRequired                        = errors.New("email is required")
	ErrWeakPassword                         = errors.New("password must be at least 8 characters")
	ErrNotMatchPassword                     = errors.New("confirmed password is not match")
	ErrEmailAlreadyExists                   = errors.New("email already registered")
	ErrUserNotFound                         = errors.New("user not found")
	ErrInvalidCredentials                   = errors.New("invalid credentials")
	ErrUserBanned                           = errors.New("user account is banned")
	ErrUserInactive                         = errors.New("user account is inactive")
	ErrInvalidToken                         = errors.New("invalid or expired token")
	ErrInvalidOTP                           = errors.New("invalid OTP code")
	ErrOTPExpired                           = errors.New("OTP code expired")
	ErrEmptyUsername                        = errors.New("username cannot be empty")
	ErrEmptyEmail                           = errors.New("email cannot be empty")
	ErrEmptyPhone                           = errors.New("phone cannot be empty")
	ErrUsernameExists                       = errors.New("username already exists")
	ErrPhoneAlreadyExists                   = errors.New("phone number already registered")
	ErrEmptyAddressLine                     = errors.New("address line cannot be empty")
	ErrEmptyUserID                          = errors.New("userID cannot be empty")
	ErrEmptyCity                            = errors.New("city cannot be empty")
	ErrSameEmail                            = errors.New("new email must be different from current email")
	ErrSamePhone                            = errors.New("new phone must be different from current phone")
	ErrEmailNotSet                          = errors.New("no email address configured for this user")
	ErrUnauthorizedUser                     = errors.New("user role not authorized")
	ErrInvalidFullName                      = errors.New("invalid full name")
	ErrInvalidGender                        = errors.New("invalid gender")
	ErrInvalidDob                           = errors.New("invalid date of birth")
	ErrNoFieldsToUpdate                     = errors.New("at least 1 field is required to update")
	ErrAddressNotFound                      = errors.New("address not found")
	ErrVerifiedEmailCannotBeUpdatedDirectly = errors.New("verified email cannot be updated directly")
	ErrCurrentEmailNotVerified              = errors.New("current email must be verified first")
	ErrCurrentPhoneNotVerified              = errors.New("current phone must be verified first")
	ErrInvalidOperation                     = errors.New("invalid operation or purpose")
	ErrTokenAlreadyUsed                     = errors.New("token has already been used")
)
