syntax = "proto3";

package catalog.v1;

option go_package = "github.com/TruongLe68/go-micro/pkg/gen/proto/go/catalog/v1;catalogv1";

service ProductService {
    rpc GetVariantsBySKUs(GetVariantsBySKURequest) returns (GetVariantsBySKUResponse);
}

message Variant {
    string id = 1;
    string product_id = 2;
    string product_name = 3;
    string sku = 4;
    map<string, string> attributes = 5;
    Price price = 6;
    string image = 7;
    bool is_active = 8;
}

message Price {
    string currency = 1;
    int32 amount = 2;
}

message GetVariantsBySKUResponse {
    repeated Variant variants = 1;
}

message GetVariantsBySKURequest {
    repeated string sku = 1;
}